### ISSUE TITLE
APP_URL environment variable doesn't seem to have an effecct

### ISSUE THREAD

**Issue by ghost** [muchobien/pocketbase-docker#21]
Hello. 
I'm currently trying to setup pocketbase like this: 
```
version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8000:8090"
    volumes:
      - /opt/pocketbase/data:/pb_data
      - /opt/pocketbase/public:/pb_public
    environment:
      - APP_URL=http://IP_ADDRESS:8000
```
Is there a reason pocketbase doesn't see this environment variable ? When I echo from inside the container it's the right value, but in mail templates pocketbase keeps using `localhost:8090`
