### ISSUE TITLE
Default username and password for admin pocket base docker

### ISSUE THREAD

**Issue by dviramontes** [muchobien/pocketbase-docker#31]
Hi, would you be open to a contribution to pocketbase and therefore pocketbase-docker 
that would allow a user to setup the default email and password for the container in the following way?

```yaml
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    environment:
      - POCKETBASE_ADMIN_EMAIL=${POCKETBASE_ADMIN_EMAIL}
      - POCKETBASE_ADMIN_PASSWORD=${POCKETBASE_ADMIN_PASSWORD}
```

Much like in postgres container you can do

```yaml
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
```

which eases friction during local development. Lmk what you think and thanks for creating an amazing project 💯
