### ISSUE TITLE
migrations dir

### ISSUE THREAD

**Issue by hyusetiawan** [muchobien/pocketbase-docker#8]
where can we specify the migrations directory?

**Comment by KROSF** [comment]
```yaml
version: "3.7"
services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --migrationsDir
      - /pb_migrations
    ports:
      - "8090:8090"
    volumes:
      - /path/to/data:/pb_data
      - /path/to/public:/pb_public #optional
      - /path/to/migrations: /pb_migrations
```

you can pass any extra flag using the command property
